name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - ipysankeywidget
  - ipywidgets
  - csv
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - voila
